const pathnames = {
    publics: {
        layout: "/",
        home: "/",
        search: "/search",
        roomdetail_id: "/roomdetail/:id",
        roomdetail: "/roomdetail",
        post: "/post",
        results: "/results",
        landlord: "/landlord",
        landlord_id: "/landlord/:id",
        resetpassword: "/reset-password",
        registerVerify: "/register",
        depositTerms: "/deposit-terms",
    },
    users: {
        layout: "/users",
        chatlayout: "/users/chat",
        favoriteposts: "favorite-posts",
        profilepage: "/users/profile-page",
        postmana: "/users/postmana",
        createposts: "/users/create-posts",
        verification: "/users/verification",
        editprofile: "/users/editprofile",
        chatapp: "/users/chatapp",
        chatpage: "/users/chat/:id",
        changepassword: "/users/changepassword",
        postpackage: "/users/postpackage",
        paymentresult: "/users/payment-result",
        history: "/users/history",
        depositResult: "/users/deposit-result",
        depositPostManagement: "/users/deposit-post-management",
    },

    admin: {
        layout: "/admin",
        dashboard: "dashboard",
        post: "post",
        transactionhistory: "transaction-history",
        hostmanagenment: "hostmanagenment",
        employeemana: "employeemana",
        usermana: "usermana",
        depositmanagement: "deposit-management",
        refundmanagement: "refund-management",
    },
}

export default pathnames;
